project:
  type: website

execute:
  echo: false
  warning: false
  # cache: false

website:
  title: "MBON Bio-Idx-WG"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



