project:
  type: website

execute:
  echo: false
  warning: false
  # cache: false

website:
  title: "MBON Bio-Idx-WG"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - surveys.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    # code-summary: "Show the code"
    code-tools: true



